export const SAVE_MOVIES_LIST = "SAVE_MOVIES_LIST";
export const SAVE_MOVIE_DETAIL = "SAVE_MOVIE_DETAIL";
export const CLEAR_MOVIE_DETAIL = "CLEAR_MOVIE_DETAIL";
export const SAVE_MOVIES_BY_PAGE = "SAVE_MOVIES_BY_PAGE";
export const CLEAN_MOVIES = "CLEAN_MOVIES";
